/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrescriptionsRouteImport } from './routes/_authenticated/prescriptions'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedMedicationsRouteImport } from './routes/_authenticated/medications'
import { Route as AuthenticatedMedicalRecordsRouteImport } from './routes/_authenticated/medical-records'
import { Route as AuthenticatedLabTestsRouteImport } from './routes/_authenticated/lab-tests'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedPrescriptionsIndexRouteImport } from './routes/_authenticated/prescriptions.index'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients.index'
import { Route as AuthenticatedMedicationsIndexRouteImport } from './routes/_authenticated/medications.index'
import { Route as AuthenticatedMedicalRecordsIndexRouteImport } from './routes/_authenticated/medical-records.index'
import { Route as AuthenticatedLabTestsIndexRouteImport } from './routes/_authenticated/lab-tests.index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedDoctorsIndexRouteImport } from './routes/_authenticated/doctors/index'
import { Route as AuthenticatedAppointmentsIndexRouteImport } from './routes/_authenticated/appointments.index'
import { Route as AuthenticatedUsersAddRouteImport } from './routes/_authenticated/users/add'
import { Route as AuthenticatedPrescriptionsNewRouteImport } from './routes/_authenticated/prescriptions.new'
import { Route as AuthenticatedPrescriptionsPrescriptionIdRouteImport } from './routes/_authenticated/prescriptions.$prescriptionId'
import { Route as AuthenticatedPatientsNewRouteImport } from './routes/_authenticated/patients.new'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients.$patientId'
import { Route as AuthenticatedMedicationsNewRouteImport } from './routes/_authenticated/medications.new'
import { Route as AuthenticatedMedicationsMedicationIdRouteImport } from './routes/_authenticated/medications.$medicationId'
import { Route as AuthenticatedMedicalRecordsNewRouteImport } from './routes/_authenticated/medical-records.new'
import { Route as AuthenticatedMedicalRecordsMedicalRecordIdRouteImport } from './routes/_authenticated/medical-records.$medicalRecordId'
import { Route as AuthenticatedLabTestsNewRouteImport } from './routes/_authenticated/lab-tests.new'
import { Route as AuthenticatedLabTestsLabTestIdRouteImport } from './routes/_authenticated/lab-tests.$labTestId'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices.new'
import { Route as AuthenticatedInvoicesInvoiceIdRouteImport } from './routes/_authenticated/invoices.$invoiceId'
import { Route as AuthenticatedDoctorsAddRouteImport } from './routes/_authenticated/doctors/add'
import { Route as AuthenticatedAppointmentsNewRouteImport } from './routes/_authenticated/appointments.new'
import { Route as AuthenticatedAppointmentsAppointmentIdRouteImport } from './routes/_authenticated/appointments.$appointmentId'
import { Route as AuthenticatedUsersUserIdEditRouteImport } from './routes/_authenticated/users/$userId.edit'
import { Route as AuthenticatedPrescriptionsPrintPrescriptionIdRouteImport } from './routes/_authenticated/prescriptions.print.$prescriptionId'
import { Route as AuthenticatedPrescriptionsEditPrescriptionIdRouteImport } from './routes/_authenticated/prescriptions.edit.$prescriptionId'
import { Route as AuthenticatedPatientsEditPatientIdRouteImport } from './routes/_authenticated/patients.edit.$patientId'
import { Route as AuthenticatedMedicationsStockMedicationIdRouteImport } from './routes/_authenticated/medications.stock.$medicationId'
import { Route as AuthenticatedMedicalRecordsEditMedicalRecordIdRouteImport } from './routes/_authenticated/medical-records.edit.$medicalRecordId'
import { Route as AuthenticatedLabTestsEditLabTestIdRouteImport } from './routes/_authenticated/lab-tests.edit.$labTestId'
import { Route as AuthenticatedInvoicesPrintInvoiceIdRouteImport } from './routes/_authenticated/invoices.print.$invoiceId'
import { Route as AuthenticatedInvoicesEditInvoiceIdRouteImport } from './routes/_authenticated/invoices.edit.$invoiceId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrescriptionsRoute =
  AuthenticatedPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMedicationsRoute =
  AuthenticatedMedicationsRouteImport.update({
    id: '/medications',
    path: '/medications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMedicalRecordsRoute =
  AuthenticatedMedicalRecordsRouteImport.update({
    id: '/medical-records',
    path: '/medical-records',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabTestsRoute = AuthenticatedLabTestsRouteImport.update({
  id: '/lab-tests',
  path: '/lab-tests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedPrescriptionsIndexRoute =
  AuthenticatedPrescriptionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPrescriptionsRoute,
  } as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedMedicationsIndexRoute =
  AuthenticatedMedicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMedicationsRoute,
  } as any)
const AuthenticatedMedicalRecordsIndexRoute =
  AuthenticatedMedicalRecordsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMedicalRecordsRoute,
  } as any)
const AuthenticatedLabTestsIndexRoute =
  AuthenticatedLabTestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLabTestsRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedDoctorsIndexRoute =
  AuthenticatedDoctorsIndexRouteImport.update({
    id: '/doctors/',
    path: '/doctors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppointmentsIndexRoute =
  AuthenticatedAppointmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppointmentsRoute,
  } as any)
const AuthenticatedUsersAddRoute = AuthenticatedUsersAddRouteImport.update({
  id: '/users/add',
  path: '/users/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrescriptionsNewRoute =
  AuthenticatedPrescriptionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPrescriptionsRoute,
  } as any)
const AuthenticatedPrescriptionsPrescriptionIdRoute =
  AuthenticatedPrescriptionsPrescriptionIdRouteImport.update({
    id: '/$prescriptionId',
    path: '/$prescriptionId',
    getParentRoute: () => AuthenticatedPrescriptionsRoute,
  } as any)
const AuthenticatedPatientsNewRoute =
  AuthenticatedPatientsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedMedicationsNewRoute =
  AuthenticatedMedicationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMedicationsRoute,
  } as any)
const AuthenticatedMedicationsMedicationIdRoute =
  AuthenticatedMedicationsMedicationIdRouteImport.update({
    id: '/$medicationId',
    path: '/$medicationId',
    getParentRoute: () => AuthenticatedMedicationsRoute,
  } as any)
const AuthenticatedMedicalRecordsNewRoute =
  AuthenticatedMedicalRecordsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMedicalRecordsRoute,
  } as any)
const AuthenticatedMedicalRecordsMedicalRecordIdRoute =
  AuthenticatedMedicalRecordsMedicalRecordIdRouteImport.update({
    id: '/$medicalRecordId',
    path: '/$medicalRecordId',
    getParentRoute: () => AuthenticatedMedicalRecordsRoute,
  } as any)
const AuthenticatedLabTestsNewRoute =
  AuthenticatedLabTestsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedLabTestsRoute,
  } as any)
const AuthenticatedLabTestsLabTestIdRoute =
  AuthenticatedLabTestsLabTestIdRouteImport.update({
    id: '/$labTestId',
    path: '/$labTestId',
    getParentRoute: () => AuthenticatedLabTestsRoute,
  } as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdRoute =
  AuthenticatedInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedDoctorsAddRoute = AuthenticatedDoctorsAddRouteImport.update({
  id: '/doctors/add',
  path: '/doctors/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppointmentsNewRoute =
  AuthenticatedAppointmentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAppointmentsRoute,
  } as any)
const AuthenticatedAppointmentsAppointmentIdRoute =
  AuthenticatedAppointmentsAppointmentIdRouteImport.update({
    id: '/$appointmentId',
    path: '/$appointmentId',
    getParentRoute: () => AuthenticatedAppointmentsRoute,
  } as any)
const AuthenticatedUsersUserIdEditRoute =
  AuthenticatedUsersUserIdEditRouteImport.update({
    id: '/users/$userId/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPrescriptionsPrintPrescriptionIdRoute =
  AuthenticatedPrescriptionsPrintPrescriptionIdRouteImport.update({
    id: '/print/$prescriptionId',
    path: '/print/$prescriptionId',
    getParentRoute: () => AuthenticatedPrescriptionsRoute,
  } as any)
const AuthenticatedPrescriptionsEditPrescriptionIdRoute =
  AuthenticatedPrescriptionsEditPrescriptionIdRouteImport.update({
    id: '/edit/$prescriptionId',
    path: '/edit/$prescriptionId',
    getParentRoute: () => AuthenticatedPrescriptionsRoute,
  } as any)
const AuthenticatedPatientsEditPatientIdRoute =
  AuthenticatedPatientsEditPatientIdRouteImport.update({
    id: '/edit/$patientId',
    path: '/edit/$patientId',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedMedicationsStockMedicationIdRoute =
  AuthenticatedMedicationsStockMedicationIdRouteImport.update({
    id: '/stock/$medicationId',
    path: '/stock/$medicationId',
    getParentRoute: () => AuthenticatedMedicationsRoute,
  } as any)
const AuthenticatedMedicalRecordsEditMedicalRecordIdRoute =
  AuthenticatedMedicalRecordsEditMedicalRecordIdRouteImport.update({
    id: '/edit/$medicalRecordId',
    path: '/edit/$medicalRecordId',
    getParentRoute: () => AuthenticatedMedicalRecordsRoute,
  } as any)
const AuthenticatedLabTestsEditLabTestIdRoute =
  AuthenticatedLabTestsEditLabTestIdRouteImport.update({
    id: '/edit/$labTestId',
    path: '/edit/$labTestId',
    getParentRoute: () => AuthenticatedLabTestsRoute,
  } as any)
const AuthenticatedInvoicesPrintInvoiceIdRoute =
  AuthenticatedInvoicesPrintInvoiceIdRouteImport.update({
    id: '/print/$invoiceId',
    path: '/print/$invoiceId',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInvoicesEditInvoiceIdRoute =
  AuthenticatedInvoicesEditInvoiceIdRouteImport.update({
    id: '/edit/$invoiceId',
    path: '/edit/$invoiceId',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/appointments': typeof AuthenticatedAppointmentsRouteWithChildren
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/lab-tests': typeof AuthenticatedLabTestsRouteWithChildren
  '/medical-records': typeof AuthenticatedMedicalRecordsRouteWithChildren
  '/medications': typeof AuthenticatedMedicationsRouteWithChildren
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/prescriptions': typeof AuthenticatedPrescriptionsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/appointments/$appointmentId': typeof AuthenticatedAppointmentsAppointmentIdRoute
  '/appointments/new': typeof AuthenticatedAppointmentsNewRoute
  '/doctors/add': typeof AuthenticatedDoctorsAddRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/lab-tests/$labTestId': typeof AuthenticatedLabTestsLabTestIdRoute
  '/lab-tests/new': typeof AuthenticatedLabTestsNewRoute
  '/medical-records/$medicalRecordId': typeof AuthenticatedMedicalRecordsMedicalRecordIdRoute
  '/medical-records/new': typeof AuthenticatedMedicalRecordsNewRoute
  '/medications/$medicationId': typeof AuthenticatedMedicationsMedicationIdRoute
  '/medications/new': typeof AuthenticatedMedicationsNewRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/patients/new': typeof AuthenticatedPatientsNewRoute
  '/prescriptions/$prescriptionId': typeof AuthenticatedPrescriptionsPrescriptionIdRoute
  '/prescriptions/new': typeof AuthenticatedPrescriptionsNewRoute
  '/users/add': typeof AuthenticatedUsersAddRoute
  '/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/doctors': typeof AuthenticatedDoctorsIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/lab-tests/': typeof AuthenticatedLabTestsIndexRoute
  '/medical-records/': typeof AuthenticatedMedicalRecordsIndexRoute
  '/medications/': typeof AuthenticatedMedicationsIndexRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/prescriptions/': typeof AuthenticatedPrescriptionsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/invoices/edit/$invoiceId': typeof AuthenticatedInvoicesEditInvoiceIdRoute
  '/invoices/print/$invoiceId': typeof AuthenticatedInvoicesPrintInvoiceIdRoute
  '/lab-tests/edit/$labTestId': typeof AuthenticatedLabTestsEditLabTestIdRoute
  '/medical-records/edit/$medicalRecordId': typeof AuthenticatedMedicalRecordsEditMedicalRecordIdRoute
  '/medications/stock/$medicationId': typeof AuthenticatedMedicationsStockMedicationIdRoute
  '/patients/edit/$patientId': typeof AuthenticatedPatientsEditPatientIdRoute
  '/prescriptions/edit/$prescriptionId': typeof AuthenticatedPrescriptionsEditPrescriptionIdRoute
  '/prescriptions/print/$prescriptionId': typeof AuthenticatedPrescriptionsPrintPrescriptionIdRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/appointments/$appointmentId': typeof AuthenticatedAppointmentsAppointmentIdRoute
  '/appointments/new': typeof AuthenticatedAppointmentsNewRoute
  '/doctors/add': typeof AuthenticatedDoctorsAddRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/lab-tests/$labTestId': typeof AuthenticatedLabTestsLabTestIdRoute
  '/lab-tests/new': typeof AuthenticatedLabTestsNewRoute
  '/medical-records/$medicalRecordId': typeof AuthenticatedMedicalRecordsMedicalRecordIdRoute
  '/medical-records/new': typeof AuthenticatedMedicalRecordsNewRoute
  '/medications/$medicationId': typeof AuthenticatedMedicationsMedicationIdRoute
  '/medications/new': typeof AuthenticatedMedicationsNewRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/patients/new': typeof AuthenticatedPatientsNewRoute
  '/prescriptions/$prescriptionId': typeof AuthenticatedPrescriptionsPrescriptionIdRoute
  '/prescriptions/new': typeof AuthenticatedPrescriptionsNewRoute
  '/users/add': typeof AuthenticatedUsersAddRoute
  '/appointments': typeof AuthenticatedAppointmentsIndexRoute
  '/doctors': typeof AuthenticatedDoctorsIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/lab-tests': typeof AuthenticatedLabTestsIndexRoute
  '/medical-records': typeof AuthenticatedMedicalRecordsIndexRoute
  '/medications': typeof AuthenticatedMedicationsIndexRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/prescriptions': typeof AuthenticatedPrescriptionsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/invoices/edit/$invoiceId': typeof AuthenticatedInvoicesEditInvoiceIdRoute
  '/invoices/print/$invoiceId': typeof AuthenticatedInvoicesPrintInvoiceIdRoute
  '/lab-tests/edit/$labTestId': typeof AuthenticatedLabTestsEditLabTestIdRoute
  '/medical-records/edit/$medicalRecordId': typeof AuthenticatedMedicalRecordsEditMedicalRecordIdRoute
  '/medications/stock/$medicationId': typeof AuthenticatedMedicationsStockMedicationIdRoute
  '/patients/edit/$patientId': typeof AuthenticatedPatientsEditPatientIdRoute
  '/prescriptions/edit/$prescriptionId': typeof AuthenticatedPrescriptionsEditPrescriptionIdRoute
  '/prescriptions/print/$prescriptionId': typeof AuthenticatedPrescriptionsPrintPrescriptionIdRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRouteWithChildren
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/_authenticated/lab-tests': typeof AuthenticatedLabTestsRouteWithChildren
  '/_authenticated/medical-records': typeof AuthenticatedMedicalRecordsRouteWithChildren
  '/_authenticated/medications': typeof AuthenticatedMedicationsRouteWithChildren
  '/_authenticated/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/_authenticated/prescriptions': typeof AuthenticatedPrescriptionsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/appointments/$appointmentId': typeof AuthenticatedAppointmentsAppointmentIdRoute
  '/_authenticated/appointments/new': typeof AuthenticatedAppointmentsNewRoute
  '/_authenticated/doctors/add': typeof AuthenticatedDoctorsAddRoute
  '/_authenticated/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/lab-tests/$labTestId': typeof AuthenticatedLabTestsLabTestIdRoute
  '/_authenticated/lab-tests/new': typeof AuthenticatedLabTestsNewRoute
  '/_authenticated/medical-records/$medicalRecordId': typeof AuthenticatedMedicalRecordsMedicalRecordIdRoute
  '/_authenticated/medical-records/new': typeof AuthenticatedMedicalRecordsNewRoute
  '/_authenticated/medications/$medicationId': typeof AuthenticatedMedicationsMedicationIdRoute
  '/_authenticated/medications/new': typeof AuthenticatedMedicationsNewRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/_authenticated/patients/new': typeof AuthenticatedPatientsNewRoute
  '/_authenticated/prescriptions/$prescriptionId': typeof AuthenticatedPrescriptionsPrescriptionIdRoute
  '/_authenticated/prescriptions/new': typeof AuthenticatedPrescriptionsNewRoute
  '/_authenticated/users/add': typeof AuthenticatedUsersAddRoute
  '/_authenticated/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/_authenticated/doctors/': typeof AuthenticatedDoctorsIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/lab-tests/': typeof AuthenticatedLabTestsIndexRoute
  '/_authenticated/medical-records/': typeof AuthenticatedMedicalRecordsIndexRoute
  '/_authenticated/medications/': typeof AuthenticatedMedicationsIndexRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/_authenticated/prescriptions/': typeof AuthenticatedPrescriptionsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/invoices/edit/$invoiceId': typeof AuthenticatedInvoicesEditInvoiceIdRoute
  '/_authenticated/invoices/print/$invoiceId': typeof AuthenticatedInvoicesPrintInvoiceIdRoute
  '/_authenticated/lab-tests/edit/$labTestId': typeof AuthenticatedLabTestsEditLabTestIdRoute
  '/_authenticated/medical-records/edit/$medicalRecordId': typeof AuthenticatedMedicalRecordsEditMedicalRecordIdRoute
  '/_authenticated/medications/stock/$medicationId': typeof AuthenticatedMedicationsStockMedicationIdRoute
  '/_authenticated/patients/edit/$patientId': typeof AuthenticatedPatientsEditPatientIdRoute
  '/_authenticated/prescriptions/edit/$prescriptionId': typeof AuthenticatedPrescriptionsEditPrescriptionIdRoute
  '/_authenticated/prescriptions/print/$prescriptionId': typeof AuthenticatedPrescriptionsPrintPrescriptionIdRoute
  '/_authenticated/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/appointments'
    | '/invoices'
    | '/lab-tests'
    | '/medical-records'
    | '/medications'
    | '/patients'
    | '/prescriptions'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/'
    | '/appointments/$appointmentId'
    | '/appointments/new'
    | '/doctors/add'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/lab-tests/$labTestId'
    | '/lab-tests/new'
    | '/medical-records/$medicalRecordId'
    | '/medical-records/new'
    | '/medications/$medicationId'
    | '/medications/new'
    | '/patients/$patientId'
    | '/patients/new'
    | '/prescriptions/$prescriptionId'
    | '/prescriptions/new'
    | '/users/add'
    | '/appointments/'
    | '/doctors'
    | '/invoices/'
    | '/lab-tests/'
    | '/medical-records/'
    | '/medications/'
    | '/patients/'
    | '/prescriptions/'
    | '/reports/'
    | '/users'
    | '/invoices/edit/$invoiceId'
    | '/invoices/print/$invoiceId'
    | '/lab-tests/edit/$labTestId'
    | '/medical-records/edit/$medicalRecordId'
    | '/medications/stock/$medicationId'
    | '/patients/edit/$patientId'
    | '/prescriptions/edit/$prescriptionId'
    | '/prescriptions/print/$prescriptionId'
    | '/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/profile'
    | '/settings'
    | '/'
    | '/appointments/$appointmentId'
    | '/appointments/new'
    | '/doctors/add'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/lab-tests/$labTestId'
    | '/lab-tests/new'
    | '/medical-records/$medicalRecordId'
    | '/medical-records/new'
    | '/medications/$medicationId'
    | '/medications/new'
    | '/patients/$patientId'
    | '/patients/new'
    | '/prescriptions/$prescriptionId'
    | '/prescriptions/new'
    | '/users/add'
    | '/appointments'
    | '/doctors'
    | '/invoices'
    | '/lab-tests'
    | '/medical-records'
    | '/medications'
    | '/patients'
    | '/prescriptions'
    | '/reports'
    | '/users'
    | '/invoices/edit/$invoiceId'
    | '/invoices/print/$invoiceId'
    | '/lab-tests/edit/$labTestId'
    | '/medical-records/edit/$medicalRecordId'
    | '/medications/stock/$medicationId'
    | '/patients/edit/$patientId'
    | '/prescriptions/edit/$prescriptionId'
    | '/prescriptions/print/$prescriptionId'
    | '/users/$userId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/appointments'
    | '/_authenticated/invoices'
    | '/_authenticated/lab-tests'
    | '/_authenticated/medical-records'
    | '/_authenticated/medications'
    | '/_authenticated/patients'
    | '/_authenticated/prescriptions'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/appointments/$appointmentId'
    | '/_authenticated/appointments/new'
    | '/_authenticated/doctors/add'
    | '/_authenticated/invoices/$invoiceId'
    | '/_authenticated/invoices/new'
    | '/_authenticated/lab-tests/$labTestId'
    | '/_authenticated/lab-tests/new'
    | '/_authenticated/medical-records/$medicalRecordId'
    | '/_authenticated/medical-records/new'
    | '/_authenticated/medications/$medicationId'
    | '/_authenticated/medications/new'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/patients/new'
    | '/_authenticated/prescriptions/$prescriptionId'
    | '/_authenticated/prescriptions/new'
    | '/_authenticated/users/add'
    | '/_authenticated/appointments/'
    | '/_authenticated/doctors/'
    | '/_authenticated/invoices/'
    | '/_authenticated/lab-tests/'
    | '/_authenticated/medical-records/'
    | '/_authenticated/medications/'
    | '/_authenticated/patients/'
    | '/_authenticated/prescriptions/'
    | '/_authenticated/reports/'
    | '/_authenticated/users/'
    | '/_authenticated/invoices/edit/$invoiceId'
    | '/_authenticated/invoices/print/$invoiceId'
    | '/_authenticated/lab-tests/edit/$labTestId'
    | '/_authenticated/medical-records/edit/$medicalRecordId'
    | '/_authenticated/medications/stock/$medicationId'
    | '/_authenticated/patients/edit/$patientId'
    | '/_authenticated/prescriptions/edit/$prescriptionId'
    | '/_authenticated/prescriptions/print/$prescriptionId'
    | '/_authenticated/users/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prescriptions': {
      id: '/_authenticated/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AuthenticatedPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medications': {
      id: '/_authenticated/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof AuthenticatedMedicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medical-records': {
      id: '/_authenticated/medical-records'
      path: '/medical-records'
      fullPath: '/medical-records'
      preLoaderRoute: typeof AuthenticatedMedicalRecordsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab-tests': {
      id: '/_authenticated/lab-tests'
      path: '/lab-tests'
      fullPath: '/lab-tests'
      preLoaderRoute: typeof AuthenticatedLabTestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/prescriptions/': {
      id: '/_authenticated/prescriptions/'
      path: '/'
      fullPath: '/prescriptions/'
      preLoaderRoute: typeof AuthenticatedPrescriptionsIndexRouteImport
      parentRoute: typeof AuthenticatedPrescriptionsRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/medications/': {
      id: '/_authenticated/medications/'
      path: '/'
      fullPath: '/medications/'
      preLoaderRoute: typeof AuthenticatedMedicationsIndexRouteImport
      parentRoute: typeof AuthenticatedMedicationsRoute
    }
    '/_authenticated/medical-records/': {
      id: '/_authenticated/medical-records/'
      path: '/'
      fullPath: '/medical-records/'
      preLoaderRoute: typeof AuthenticatedMedicalRecordsIndexRouteImport
      parentRoute: typeof AuthenticatedMedicalRecordsRoute
    }
    '/_authenticated/lab-tests/': {
      id: '/_authenticated/lab-tests/'
      path: '/'
      fullPath: '/lab-tests/'
      preLoaderRoute: typeof AuthenticatedLabTestsIndexRouteImport
      parentRoute: typeof AuthenticatedLabTestsRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/doctors/': {
      id: '/_authenticated/doctors/'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AuthenticatedDoctorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments/': {
      id: '/_authenticated/appointments/'
      path: '/'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AuthenticatedAppointmentsIndexRouteImport
      parentRoute: typeof AuthenticatedAppointmentsRoute
    }
    '/_authenticated/users/add': {
      id: '/_authenticated/users/add'
      path: '/users/add'
      fullPath: '/users/add'
      preLoaderRoute: typeof AuthenticatedUsersAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prescriptions/new': {
      id: '/_authenticated/prescriptions/new'
      path: '/new'
      fullPath: '/prescriptions/new'
      preLoaderRoute: typeof AuthenticatedPrescriptionsNewRouteImport
      parentRoute: typeof AuthenticatedPrescriptionsRoute
    }
    '/_authenticated/prescriptions/$prescriptionId': {
      id: '/_authenticated/prescriptions/$prescriptionId'
      path: '/$prescriptionId'
      fullPath: '/prescriptions/$prescriptionId'
      preLoaderRoute: typeof AuthenticatedPrescriptionsPrescriptionIdRouteImport
      parentRoute: typeof AuthenticatedPrescriptionsRoute
    }
    '/_authenticated/patients/new': {
      id: '/_authenticated/patients/new'
      path: '/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AuthenticatedPatientsNewRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/medications/new': {
      id: '/_authenticated/medications/new'
      path: '/new'
      fullPath: '/medications/new'
      preLoaderRoute: typeof AuthenticatedMedicationsNewRouteImport
      parentRoute: typeof AuthenticatedMedicationsRoute
    }
    '/_authenticated/medications/$medicationId': {
      id: '/_authenticated/medications/$medicationId'
      path: '/$medicationId'
      fullPath: '/medications/$medicationId'
      preLoaderRoute: typeof AuthenticatedMedicationsMedicationIdRouteImport
      parentRoute: typeof AuthenticatedMedicationsRoute
    }
    '/_authenticated/medical-records/new': {
      id: '/_authenticated/medical-records/new'
      path: '/new'
      fullPath: '/medical-records/new'
      preLoaderRoute: typeof AuthenticatedMedicalRecordsNewRouteImport
      parentRoute: typeof AuthenticatedMedicalRecordsRoute
    }
    '/_authenticated/medical-records/$medicalRecordId': {
      id: '/_authenticated/medical-records/$medicalRecordId'
      path: '/$medicalRecordId'
      fullPath: '/medical-records/$medicalRecordId'
      preLoaderRoute: typeof AuthenticatedMedicalRecordsMedicalRecordIdRouteImport
      parentRoute: typeof AuthenticatedMedicalRecordsRoute
    }
    '/_authenticated/lab-tests/new': {
      id: '/_authenticated/lab-tests/new'
      path: '/new'
      fullPath: '/lab-tests/new'
      preLoaderRoute: typeof AuthenticatedLabTestsNewRouteImport
      parentRoute: typeof AuthenticatedLabTestsRoute
    }
    '/_authenticated/lab-tests/$labTestId': {
      id: '/_authenticated/lab-tests/$labTestId'
      path: '/$labTestId'
      fullPath: '/lab-tests/$labTestId'
      preLoaderRoute: typeof AuthenticatedLabTestsLabTestIdRouteImport
      parentRoute: typeof AuthenticatedLabTestsRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/invoices/$invoiceId': {
      id: '/_authenticated/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/doctors/add': {
      id: '/_authenticated/doctors/add'
      path: '/doctors/add'
      fullPath: '/doctors/add'
      preLoaderRoute: typeof AuthenticatedDoctorsAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments/new': {
      id: '/_authenticated/appointments/new'
      path: '/new'
      fullPath: '/appointments/new'
      preLoaderRoute: typeof AuthenticatedAppointmentsNewRouteImport
      parentRoute: typeof AuthenticatedAppointmentsRoute
    }
    '/_authenticated/appointments/$appointmentId': {
      id: '/_authenticated/appointments/$appointmentId'
      path: '/$appointmentId'
      fullPath: '/appointments/$appointmentId'
      preLoaderRoute: typeof AuthenticatedAppointmentsAppointmentIdRouteImport
      parentRoute: typeof AuthenticatedAppointmentsRoute
    }
    '/_authenticated/users/$userId/edit': {
      id: '/_authenticated/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof AuthenticatedUsersUserIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prescriptions/print/$prescriptionId': {
      id: '/_authenticated/prescriptions/print/$prescriptionId'
      path: '/print/$prescriptionId'
      fullPath: '/prescriptions/print/$prescriptionId'
      preLoaderRoute: typeof AuthenticatedPrescriptionsPrintPrescriptionIdRouteImport
      parentRoute: typeof AuthenticatedPrescriptionsRoute
    }
    '/_authenticated/prescriptions/edit/$prescriptionId': {
      id: '/_authenticated/prescriptions/edit/$prescriptionId'
      path: '/edit/$prescriptionId'
      fullPath: '/prescriptions/edit/$prescriptionId'
      preLoaderRoute: typeof AuthenticatedPrescriptionsEditPrescriptionIdRouteImport
      parentRoute: typeof AuthenticatedPrescriptionsRoute
    }
    '/_authenticated/patients/edit/$patientId': {
      id: '/_authenticated/patients/edit/$patientId'
      path: '/edit/$patientId'
      fullPath: '/patients/edit/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsEditPatientIdRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/medications/stock/$medicationId': {
      id: '/_authenticated/medications/stock/$medicationId'
      path: '/stock/$medicationId'
      fullPath: '/medications/stock/$medicationId'
      preLoaderRoute: typeof AuthenticatedMedicationsStockMedicationIdRouteImport
      parentRoute: typeof AuthenticatedMedicationsRoute
    }
    '/_authenticated/medical-records/edit/$medicalRecordId': {
      id: '/_authenticated/medical-records/edit/$medicalRecordId'
      path: '/edit/$medicalRecordId'
      fullPath: '/medical-records/edit/$medicalRecordId'
      preLoaderRoute: typeof AuthenticatedMedicalRecordsEditMedicalRecordIdRouteImport
      parentRoute: typeof AuthenticatedMedicalRecordsRoute
    }
    '/_authenticated/lab-tests/edit/$labTestId': {
      id: '/_authenticated/lab-tests/edit/$labTestId'
      path: '/edit/$labTestId'
      fullPath: '/lab-tests/edit/$labTestId'
      preLoaderRoute: typeof AuthenticatedLabTestsEditLabTestIdRouteImport
      parentRoute: typeof AuthenticatedLabTestsRoute
    }
    '/_authenticated/invoices/print/$invoiceId': {
      id: '/_authenticated/invoices/print/$invoiceId'
      path: '/print/$invoiceId'
      fullPath: '/invoices/print/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesPrintInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/invoices/edit/$invoiceId': {
      id: '/_authenticated/invoices/edit/$invoiceId'
      path: '/edit/$invoiceId'
      fullPath: '/invoices/edit/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesEditInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
  }
}

interface AuthenticatedAppointmentsRouteChildren {
  AuthenticatedAppointmentsAppointmentIdRoute: typeof AuthenticatedAppointmentsAppointmentIdRoute
  AuthenticatedAppointmentsNewRoute: typeof AuthenticatedAppointmentsNewRoute
  AuthenticatedAppointmentsIndexRoute: typeof AuthenticatedAppointmentsIndexRoute
}

const AuthenticatedAppointmentsRouteChildren: AuthenticatedAppointmentsRouteChildren =
  {
    AuthenticatedAppointmentsAppointmentIdRoute:
      AuthenticatedAppointmentsAppointmentIdRoute,
    AuthenticatedAppointmentsNewRoute: AuthenticatedAppointmentsNewRoute,
    AuthenticatedAppointmentsIndexRoute: AuthenticatedAppointmentsIndexRoute,
  }

const AuthenticatedAppointmentsRouteWithChildren =
  AuthenticatedAppointmentsRoute._addFileChildren(
    AuthenticatedAppointmentsRouteChildren,
  )

interface AuthenticatedInvoicesRouteChildren {
  AuthenticatedInvoicesInvoiceIdRoute: typeof AuthenticatedInvoicesInvoiceIdRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedInvoicesEditInvoiceIdRoute: typeof AuthenticatedInvoicesEditInvoiceIdRoute
  AuthenticatedInvoicesPrintInvoiceIdRoute: typeof AuthenticatedInvoicesPrintInvoiceIdRoute
}

const AuthenticatedInvoicesRouteChildren: AuthenticatedInvoicesRouteChildren = {
  AuthenticatedInvoicesInvoiceIdRoute: AuthenticatedInvoicesInvoiceIdRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedInvoicesEditInvoiceIdRoute:
    AuthenticatedInvoicesEditInvoiceIdRoute,
  AuthenticatedInvoicesPrintInvoiceIdRoute:
    AuthenticatedInvoicesPrintInvoiceIdRoute,
}

const AuthenticatedInvoicesRouteWithChildren =
  AuthenticatedInvoicesRoute._addFileChildren(
    AuthenticatedInvoicesRouteChildren,
  )

interface AuthenticatedLabTestsRouteChildren {
  AuthenticatedLabTestsLabTestIdRoute: typeof AuthenticatedLabTestsLabTestIdRoute
  AuthenticatedLabTestsNewRoute: typeof AuthenticatedLabTestsNewRoute
  AuthenticatedLabTestsIndexRoute: typeof AuthenticatedLabTestsIndexRoute
  AuthenticatedLabTestsEditLabTestIdRoute: typeof AuthenticatedLabTestsEditLabTestIdRoute
}

const AuthenticatedLabTestsRouteChildren: AuthenticatedLabTestsRouteChildren = {
  AuthenticatedLabTestsLabTestIdRoute: AuthenticatedLabTestsLabTestIdRoute,
  AuthenticatedLabTestsNewRoute: AuthenticatedLabTestsNewRoute,
  AuthenticatedLabTestsIndexRoute: AuthenticatedLabTestsIndexRoute,
  AuthenticatedLabTestsEditLabTestIdRoute:
    AuthenticatedLabTestsEditLabTestIdRoute,
}

const AuthenticatedLabTestsRouteWithChildren =
  AuthenticatedLabTestsRoute._addFileChildren(
    AuthenticatedLabTestsRouteChildren,
  )

interface AuthenticatedMedicalRecordsRouteChildren {
  AuthenticatedMedicalRecordsMedicalRecordIdRoute: typeof AuthenticatedMedicalRecordsMedicalRecordIdRoute
  AuthenticatedMedicalRecordsNewRoute: typeof AuthenticatedMedicalRecordsNewRoute
  AuthenticatedMedicalRecordsIndexRoute: typeof AuthenticatedMedicalRecordsIndexRoute
  AuthenticatedMedicalRecordsEditMedicalRecordIdRoute: typeof AuthenticatedMedicalRecordsEditMedicalRecordIdRoute
}

const AuthenticatedMedicalRecordsRouteChildren: AuthenticatedMedicalRecordsRouteChildren =
  {
    AuthenticatedMedicalRecordsMedicalRecordIdRoute:
      AuthenticatedMedicalRecordsMedicalRecordIdRoute,
    AuthenticatedMedicalRecordsNewRoute: AuthenticatedMedicalRecordsNewRoute,
    AuthenticatedMedicalRecordsIndexRoute:
      AuthenticatedMedicalRecordsIndexRoute,
    AuthenticatedMedicalRecordsEditMedicalRecordIdRoute:
      AuthenticatedMedicalRecordsEditMedicalRecordIdRoute,
  }

const AuthenticatedMedicalRecordsRouteWithChildren =
  AuthenticatedMedicalRecordsRoute._addFileChildren(
    AuthenticatedMedicalRecordsRouteChildren,
  )

interface AuthenticatedMedicationsRouteChildren {
  AuthenticatedMedicationsMedicationIdRoute: typeof AuthenticatedMedicationsMedicationIdRoute
  AuthenticatedMedicationsNewRoute: typeof AuthenticatedMedicationsNewRoute
  AuthenticatedMedicationsIndexRoute: typeof AuthenticatedMedicationsIndexRoute
  AuthenticatedMedicationsStockMedicationIdRoute: typeof AuthenticatedMedicationsStockMedicationIdRoute
}

const AuthenticatedMedicationsRouteChildren: AuthenticatedMedicationsRouteChildren =
  {
    AuthenticatedMedicationsMedicationIdRoute:
      AuthenticatedMedicationsMedicationIdRoute,
    AuthenticatedMedicationsNewRoute: AuthenticatedMedicationsNewRoute,
    AuthenticatedMedicationsIndexRoute: AuthenticatedMedicationsIndexRoute,
    AuthenticatedMedicationsStockMedicationIdRoute:
      AuthenticatedMedicationsStockMedicationIdRoute,
  }

const AuthenticatedMedicationsRouteWithChildren =
  AuthenticatedMedicationsRoute._addFileChildren(
    AuthenticatedMedicationsRouteChildren,
  )

interface AuthenticatedPatientsRouteChildren {
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
  AuthenticatedPatientsNewRoute: typeof AuthenticatedPatientsNewRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
  AuthenticatedPatientsEditPatientIdRoute: typeof AuthenticatedPatientsEditPatientIdRoute
}

const AuthenticatedPatientsRouteChildren: AuthenticatedPatientsRouteChildren = {
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
  AuthenticatedPatientsNewRoute: AuthenticatedPatientsNewRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
  AuthenticatedPatientsEditPatientIdRoute:
    AuthenticatedPatientsEditPatientIdRoute,
}

const AuthenticatedPatientsRouteWithChildren =
  AuthenticatedPatientsRoute._addFileChildren(
    AuthenticatedPatientsRouteChildren,
  )

interface AuthenticatedPrescriptionsRouteChildren {
  AuthenticatedPrescriptionsPrescriptionIdRoute: typeof AuthenticatedPrescriptionsPrescriptionIdRoute
  AuthenticatedPrescriptionsNewRoute: typeof AuthenticatedPrescriptionsNewRoute
  AuthenticatedPrescriptionsIndexRoute: typeof AuthenticatedPrescriptionsIndexRoute
  AuthenticatedPrescriptionsEditPrescriptionIdRoute: typeof AuthenticatedPrescriptionsEditPrescriptionIdRoute
  AuthenticatedPrescriptionsPrintPrescriptionIdRoute: typeof AuthenticatedPrescriptionsPrintPrescriptionIdRoute
}

const AuthenticatedPrescriptionsRouteChildren: AuthenticatedPrescriptionsRouteChildren =
  {
    AuthenticatedPrescriptionsPrescriptionIdRoute:
      AuthenticatedPrescriptionsPrescriptionIdRoute,
    AuthenticatedPrescriptionsNewRoute: AuthenticatedPrescriptionsNewRoute,
    AuthenticatedPrescriptionsIndexRoute: AuthenticatedPrescriptionsIndexRoute,
    AuthenticatedPrescriptionsEditPrescriptionIdRoute:
      AuthenticatedPrescriptionsEditPrescriptionIdRoute,
    AuthenticatedPrescriptionsPrintPrescriptionIdRoute:
      AuthenticatedPrescriptionsPrintPrescriptionIdRoute,
  }

const AuthenticatedPrescriptionsRouteWithChildren =
  AuthenticatedPrescriptionsRoute._addFileChildren(
    AuthenticatedPrescriptionsRouteChildren,
  )

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRouteWithChildren
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRouteWithChildren
  AuthenticatedLabTestsRoute: typeof AuthenticatedLabTestsRouteWithChildren
  AuthenticatedMedicalRecordsRoute: typeof AuthenticatedMedicalRecordsRouteWithChildren
  AuthenticatedMedicationsRoute: typeof AuthenticatedMedicationsRouteWithChildren
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRouteWithChildren
  AuthenticatedPrescriptionsRoute: typeof AuthenticatedPrescriptionsRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDoctorsAddRoute: typeof AuthenticatedDoctorsAddRoute
  AuthenticatedUsersAddRoute: typeof AuthenticatedUsersAddRoute
  AuthenticatedDoctorsIndexRoute: typeof AuthenticatedDoctorsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedUsersUserIdEditRoute: typeof AuthenticatedUsersUserIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRouteWithChildren,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRouteWithChildren,
  AuthenticatedLabTestsRoute: AuthenticatedLabTestsRouteWithChildren,
  AuthenticatedMedicalRecordsRoute:
    AuthenticatedMedicalRecordsRouteWithChildren,
  AuthenticatedMedicationsRoute: AuthenticatedMedicationsRouteWithChildren,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRouteWithChildren,
  AuthenticatedPrescriptionsRoute: AuthenticatedPrescriptionsRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDoctorsAddRoute: AuthenticatedDoctorsAddRoute,
  AuthenticatedUsersAddRoute: AuthenticatedUsersAddRoute,
  AuthenticatedDoctorsIndexRoute: AuthenticatedDoctorsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedUsersUserIdEditRoute: AuthenticatedUsersUserIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
